# Generated by Django 4.2.16 on 2024-12-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='processed',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='columns_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='rows_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='file_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
