# Generated by Django 5.1.4 on 2024-12-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_App', '0002_alter_excelfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
