# Generated by Django 5.1.4 on 2024-12-07 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_App', '0003_alter_excelfile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excel_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
