# Generated by Django 4.2.16 on 2024-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel_App', '0005_excelfile_last_modified_alter_excelfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='has_been_edited',
            field=models.BooleanField(default=False),
        ),
    ]
